services:
  my-mysql-db:
    container_name: my-mysql-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restdb
      MYSQL_USER: restadmin
      MYSQL_PASSWORD: password
    expose:
      - "3306"
  my-mongo-db:
    container_name: my-mongo-db
    image: mongo:latest
    expose:
      - "27017"
  spring-practice-auth-server:
    container_name: spring-practice-auth-server
    image: spring-practice-auth-server:0.0.1-SNAPSHOT
    expose:
      - "9000"